[Param]
workdir = /home/patrick/projects/Microbion/genomics/icefinder2

## For Metagenome Input
kraken = /home/patrick/projects/Microbion/genomics/kraken2/kraken2
# Existing broad Kraken2 database; replace if you want a project-specific taxonomy DB.
krakenDB = /home/patrick/projects/Microbion/genomics/kraken2/k2_pluspf_20220908
###
# Optional
#mmseqs = /home/patrick/projects/MMseqs2/build/bin/mmseqs
#mmseqDB = /Your/Path/to/mmseqs2/
defensefinder = /home/patrick/projects/Microbion/genomics/icefinder2/.venv/bin/defense-finder
blastp = /usr/bin/blastp
blastn = /usr/bin/blastn
seqkit = /usr/local/bin/seqkit
prodigal = /usr/bin/prodigal
prokka = /home/patrick/projects/prokka/bin/prokka
macsyfinder = /home/patrick/projects/Microbion/genomics/icefinder2/.venv/bin/macsyfinder
hmmsearch = /usr/bin/hmmsearch
